queue_rules:
  - name: vm1-close-reopen
    queue_conditions:
      - title = VM1_QUEUE_CLOSE_REOPEN
    merge_conditions:
      - label = vm1-never-merge-close-reopen
    checks_timeout: null
pull_request_rules: []
