pull_request_rules:
  - name: VM1_CONFIG_RELOCATION_TRUE
    conditions:
      - mergify-configuration-changed
    actions:
      label:
        add:
          - vm1-config-relocation-true
  - name: VM1_CONFIG_RELOCATION_FALSE
    conditions:
      - -mergify-configuration-changed
    actions:
      label:
        add:
          - vm1-config-relocation-false
